Update django.yml

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -17,6 +17,7 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.11"
+          cache: "pip"
 
       - name: Install Python Dependencies
         run: |
@@ -46,6 +47,7 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.11"
+          cache: "pip"
 
       - name: Install Dependencies
         run: |
@@ -129,4 +131,21 @@ jobs:
           version_label: build-${{ github.run_number }}
           deployment_package: deploy.zip
           use_existing_version_if_available: true
-          wait_for_deployment: true
+          wait_for_deployment: false
+
+      - name: Wait for Application
+        run: sleep 30
+
+      - name: Verify Deployment
+        run: |
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://expensetracker.us-east-1.elasticbeanstalk.com)
+
+          echo "Application returned HTTP status: $STATUS"
+
+          if [ "$STATUS" = "200" ] || [ "$STATUS" = "302" ]; then
+            echo "Deployment successful!"
+            exit 0
+          else
+            echo "Deployment verification failed."
+            exit 1
+          fi
